### ISSUE TITLE
No content after first paragraph of $body$

### ISSUE THREAD

**Issue by brentthorne** [brentthorne/pagedown#4]
When adding content to the `$body$` only a single page will render and then any content after the first paragraph will not show

**Comment by brentthorne** [comment]
This is for the mdpi_paged branch that I have started. Not sure if I am missing something in the css. Not sure if @RLesur has suggestions.

**Comment by brentthorne** [comment]
So this is the behaviour when running `xaringan::inf_mr()` and opening the output in chrome. When opening in firefox it acts fine.

**Comment by RLesur** [comment]
I had a hard time figuring out where was the problem. 
I think I've found it, see my comments https://github.com/brentthorne/pagedown/commit/59a365ac3319387041859c56561ca51fc6c9b41e#r34186670 and https://github.com/brentthorne/pagedown/commit/59a365ac3319387041859c56561ca51fc6c9b41e#r34186688

**Comment by brentthorne** [comment]
Thanks that did it. Now I just need to figure out how to get the proper font working and things should be ready to go soon. Firefox has it right but chrome's `Palatino Linotype` is off from what the journal uses.
